### ISSUE TITLE
Issue with naming the node.js application ratings

### ISSUE THREAD

**Issue by hsternkicker** [RayMoz/training-bookinfo#4]
When doing the part 2 of the training, the first lab part is to rename the node.js application. The code prepared for the package.json is used as 
"name": "{My name} ratings",
But spaces are not allowed in the name of the node.js application. be sure to use only none space characters in the name value, otherwise the node-modules will not be loaded with the resulting package.json.

**Comment by RayMoz** [comment]
Thx Henning ... I corrected the file and put a dash in the name.
